# Generated by Django 6.0.4 on 2026-04-21 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_number', models.CharField(max_length=50)),
                ('total_seats', models.IntegerField()),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='theatres.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=20)),
                ('seat_type', models.CharField(choices=[('VIP', 'VIP'), ('NORMAL', 'Normal')], default='NORMAL', max_length=20)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='theatres.screen')),
            ],
            options={
                'unique_together': {('screen', 'seat_number')},
            },
        ),
    ]
