# Generated by Django 5.2.4 on 2026-04-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('THEATRE_MANAGER', 'Theatre Manager'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20),
        ),
    ]
