# Generated by Django 5.2.4 on 2026-04-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rewards_points',
            field=models.IntegerField(default=0),
        ),
    ]
